# Configuration for subscribers to cmd_vel sources.
# Typically automatic controllers should have the minimum priority
#
#
# Individual subscriber configuration:
#   name:           Source name
#   topic:          The topic that provides cmd_vel messages
#   timeout:        Time in seconds without incoming messages to consider this topic inactive
#   priority:       Priority: an UNIQUE unsigned integer from 0 (lowest) to MAX_INT
#   short_desc:     Short description (optional)

subscribers:
  - name:        "RQT Robot Steering"
    topic:       "/robot1/rqt/cmd_vel"
    timeout:     0.1
    priority:    3

  - name:        "PS3 Controller"
    topic:       "/robot1/ps3joy/cmd_vel"
    timeout:     0.1
    priority:    1

  - name:        "MoveBase (ROS Navigation)"
    topic:       "/robot1/move_base/cmd_vel"
    timeout:     0.1
    priority:    2

publisher:       "/robot1/cmd_vel"
