# 2D Costmap parameters 

transform_tolerance:        0.5 # 0.2

footprint: [ [0.27, 0.23], [0.27, -0.23], [-0.27, -0.23], [-0.27, 0.23] ]
footprint_padding: 0.05

map_type: costmap

update_frequency:           2
publish_frequency:          2
min_obstacle_height:        0.0
max_obstacle_height:        0.6 # 2.0
obstacle_range:             8.0
raytrace_range:             8.0
cost_scaling_factor:        10.0

static:
  enable: true
  unknown_cost_value:     255
  lethal_cost_threshold:  100
  track_unknown_space:    true

  # map_topic: /map

### Sensor management parameters ###
obstacles_laser:
  enabled: true
  track_unknown_space: true
  combination_method: 1
  observation_sources: laserscan
  laserscan: {  
    observation_persistence:  5.0,
    expected_update_rate:     0.0,
    data_type:                LaserScan, 
    clearing:                 true, 
    marking:                  true, 
    max_obstacle_height:      1.6,
    min_obstacle_height:      0.0,
    obstacle_range:           8.0,
    raytrace_range:           8.0
  }


obstacles_laser_local:
  enabled: true
  track_unknown_space: false
  combination_method: 1
  observation_sources: laserscan
  laserscan: {  
    observation_persistence:  5.0,
    expected_update_rate:     0.0,
    data_type:                LaserScan, 
    clearing:                 true, 
    marking:                  true, 
    max_obstacle_height:      1.6,
    min_obstacle_height:      0.0,
    obstacle_range:           8.0,
    raytrace_range:           8.0
  }

inflation:
    enabled: true
    inflation_radius: 0.25
    cost_scaling_factor: 1.5

