global_costmap:
  update_frequency:       0.5
  publish_frequency:      0.5
 
  static_map:             true
  rolling_window:         false
  # unknown_cost_value:     255
  publish_voxel_map:      false
  # lethal_cost_threshold:  100

  width:                 10
  height:                10
  resolution:            0.05
  origin_x:              0.0
  origin_y:              0.0

  # track_unknown_space:    true
  
  plugins:
    - {name: static,                  type: "costmap_2d::StaticLayer"}
    - {name: obstacles_laser,         type: "costmap_2d::VoxelLayer"}
    - {name: inflation,               type: "costmap_2d::InflationLayer"}
  
  
        
