local_costmap:
  update_frequency:       10.0   # 10.0
  publish_frequency:      5.0   # 2.0 
    
  static_map:             false  
  rolling_window:         true
  # unknown_cost_value:     255
  publish_voxel_map:      false
  # lethal_cost_threshold:  100

  width:                  3.0     # 5.0
  height:                 3.0     # 5.0
  resolution:             0.02    # 0.1
  origin_x:               0.0
  origin_y:               0.0

  # track_unknown_space:    false 
  
  plugins:
    - {name: obstacles_laser_local,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}